version: "3"
services:
  nifi:
    image: apache/nifi:1.26.0
    container_name: nifi
    ports:
      - "8080:8080"
    environment:
      - NIFI_WEB_HTTP_PORT=8080
    volumes:
      
      - ./nifi_data/flowfile:/opt/nifi/flowfile_repository
      - ./nifi_data/database:/opt/nifi/database_repository
      - ./nifi_data/content:/opt/nifi/content_repository
      - ./nifi_data/provenance:/opt/nifi/provenance_repository
      - ./logs:/opt/nifi/logs
